server:
  port: 9002

spring:
  application:
    name: USER-SERVICE
  cloud:
    config:
      enabled: true
      uri: http://localhost:9296
  config:
    import: "optional:configserver:"
  zipkin:
    base-url: http://127.0.0.1:9411/